### ISSUE TITLE
Misleading Info on Network Proposal EndBlockHeight

### ISSUE THREAD

**Issue by sdpisreddevil** [sudoblockio/icon-tracker-frontend#303] opened 2023-08-07 16:12 UTC
In Network Proposal description page, the End Blockheight shows the time as UTC but it's the local time. It's misleading which caused the expiration of the proposal. 

Screenshot for recently submitted and approved but expired proposal.

<img width="1188" alt="image" src="https://github.com/sudoblockio/icon-tracker-frontend/assets/25897013/395f4b72-7ce1-4977-a6d9-97bdf047a457">

**Comment by robcxyz** [comment] 2023-08-29 05:25
Duplicate of #302 - Will merge fix soon since we are doing major upgrade now

**Closed by robcxyz** 2023-08-29 05:25 UTC
